#!/usr/bin/env ruby

def red_alert message
  "\033[31m #{message} \033[0m\n"
end

def green_alert message
  "\033[32m #{message} \033[0m\n"
end

unless ARGV.first
  puts red_alert :"Please provide a project name! "
  exit 1
end
